main: com.stardevllc.starchat.StarChat
version: ${version}
api-version: 1.20
name: ${name}
author: Firestar311
depend: [Vault, StarCore]
softdepend: [PlaceholderAPI]
commands: 
  chat:
    aliases: [ch]
  message:
    aliases: [msg]
  reply:
    aliases: [r]